version: '3.8'

services:

  instance:
    container_name: instance
    image: mongo
    command: mongos --configdb cfgrs/192.168.124.7:10001,192.168.124.7:10002 --bind_ip 0.0.0.0 --port 27017
    ports:
      - 30000:27017